"""Embed the same reviewed manifests in the native result-validation boundary."""
import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root))
from site_adapters.validation import validate
manifests = [json.loads(path.read_text()) for path in sorted((root / "site_adapters").glob("*/manifest.json"))]
for manifest in manifests:
    validate(manifest)
assert len({item["id"] for item in manifests}) == len(manifests)
encoded = json.dumps({item["id"]: item for item in manifests}, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
delimiter = "#"
while '"' + delimiter in encoded or "\\" + delimiter in encoded:
    delimiter += "#"
content = '// Generated by scripts/sync-site-adapters.py; edit site_adapters/*/manifest.json.\nimport Foundation\nimport PolicyCore\n\nenum PackagedAdapters {\n    static let manifests = try! BoundedJSON.parse(Data(' + delimiter + '"' + encoded + '"' + delimiter + '.utf8), maximumDepth: 16)\n}\n'
target = root / "Sources/BrokerHost/PackagedAdapters.swift"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != content:
        raise SystemExit("adapter_manifest_out_of_date")
else:
    target.write_text(content)
