"""Embed the authoritative public schema in native and guest distributions."""

import json
from pathlib import Path
import sys

root = Path(__file__).resolve().parents[1]
schema = json.loads((root / "contracts/agent-api-v1.schema.json").read_text())
response = json.loads((root / "contracts/agent-result-v1.schema.json").read_text())
def check_supported(rule):
    supported = {"$schema", "$id", "title", "type", "additionalProperties", "required", "properties", "oneOf", "const", "enum", "minItems", "maxItems", "uniqueItems", "items", "maxLength", "minLength", "pattern", "format", "minimum", "maximum"}
    if not set(rule).issubset(supported) or ("type" in rule and rule["type"] not in {"object", "array", "string", "integer", "boolean", "null"}):
        raise SystemExit("unsupported_contract_feature")
    if rule.get("additionalProperties", False) is not False or rule.get("format", "uuid") != "uuid":
        raise SystemExit("unsupported_contract_feature")
    for child in rule.get("properties", {}).values():
        check_supported(child)
    for child in rule.get("oneOf", []):
        check_supported(child)
    if "items" in rule:
        check_supported(rule["items"])
check_supported(schema)
check_supported(response)
compact = json.dumps(schema, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
compact_response = json.dumps(response, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
swift = '// Generated by scripts/sync-agent-contract.py; edit contracts/agent-api-v1.schema.json.\nimport Foundation\nimport PolicyCore\n\nenum AgentContract {\n    static let schema = try! BoundedJSON.parse(Data(#"' + compact + '"#.utf8), maximumDepth: 16, maximumNodes: 8192)\n}\n'
artifacts = {
    root / "Sources/BrokerHost/AgentAPI/AgentContract.swift": swift,
    root / "agent_tools/agent-api-v1.schema.json": json.dumps(schema, indent=2) + "\n",
    root / "agent_tools/agent-result-v1.schema.json": json.dumps(response, indent=2) + "\n",
}
swift_response = '    static let responseSchema = try! BoundedJSON.parse(Data(#"' + compact_response + '"#.utf8), maximumDepth: 16, maximumNodes: 8192)\n'
artifacts[root / "Sources/BrokerHost/AgentAPI/AgentContract.swift"] = swift[:-2] + swift_response + '}\n'
for path, content in artifacts.items():
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != content:
            raise SystemExit("agent_contract_out_of_date")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
